version: '3'
services:
  web1:
    container_name: flask-container_1
    build: .
    ports:
      - '8000'
    environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASS=${REDIS_PASS}
    depends_on:
            - redis
  web2:
    container_name: flask-container_2
    build: .
    ports:
      - '8001'
    environment:

            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASS=${REDIS_PASS}

    depends_on:
            - redis

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379"
    volumes:
       - redis-data:/data    
    command: redis-server --requirepass ${REDIS_PASS}
  haproxy:
        build: ./haproxy
        container_name: haproxy
        ports:
            - "80:80"
            - "443:443"
            - "8404:8404"  
        depends_on:
            - redis  

volumes:
 redis-data:
         driver: local        
